apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-webui
  template:
    metadata:
      labels:
        app: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:1.1.0
          env:
            - name: API_BASE_URL
              value: http://garage:3903
            - name: S3_ENDPOINT_URL
              value: http://garage:3900
            - name: S3_REGION
              value: garage
            - name: API_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: GARAGE_ADMIN_TOKEN
            - name: AUTH_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: WEBUI_AUTH_USER_PASS
          ports:
            - containerPort: 3909
          readinessProbe:
            httpGet:
              path: /
              port: 3909
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3909
            initialDelaySeconds: 15
            periodSeconds: 30
