apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jankbot
  namespace: argocd
  labels:
    group: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd-image-updater.argoproj.io/image-list: "core=ghcr.io/wuguishifu/universe/jankbot-core:latest,gateway=ghcr.io/wuguishifu/universe/jankbot-gateway:latest"
    argocd-image-updater.argoproj.io/core.update-strategy: digest
    argocd-image-updater.argoproj.io/gateway.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wuguishifu/homelab.git
    targetRevision: HEAD
    path: manifests/jankbot
  destination:
    server: https://kubernetes.default.svc
    namespace: jankbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
