apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janktm-clay-saturn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: saturn=ghcr.io/janktm/jam/saturn:latest
    argocd-image-updater.argoproj.io/saturn.update-strategy: digest
    argocd-image-updater.argoproj.io/saturn.pull-secret: secret:argocd/ghcr-janktm-credentials#credentials
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/wuguishifu/homelab.git
    targetRevision: HEAD
    path: manifests/janktm/clay/saturn
  destination:
    name: home-server
    namespace: clay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
