apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thermo-automation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/wuguishifu/homelab.git
    targetRevision: HEAD
    path: manifests/thermo-automation
  destination:
    server: https://kubernetes.default.svc
    namespace: thermo-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
