apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets
  namespace: argocd
  labels:
    group: infisical
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/wuguishifu/homelab.git
    targetRevision: HEAD
    path: manifests/infisical-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 10m
