apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: argocd-image-updater-secret
  namespace: infisical-operator-system
spec:
  hostAPI: https://infisical.wuguishifu.dev/api
  syncConfig:
    resyncInterval: 60s

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: homelab
        envSlug: prod
        secretsPath: /argocd/image-updater
        recursive: false

  managedSecretReference:
    secretName: argocd-image-updater-secret
    secretNamespace: argocd
    secretType: Opaque
