apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: backup-manager-secrets
  namespace: infisical-operator-system
spec:
  hostAPI: https://infisical.wuguishifu.dev/api
  syncConfig:
    resyncInterval: 60s

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: homelab
        envSlug: prod
        secretsPath: /databases/backup
        recursive: false

  managedSecretReference:
    secretName: backup-manager-secrets
    secretNamespace: backup-manager
    secretType: Opaque
