apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tungsten-secrets
  namespace: infisical-operator-system
spec:
  hostAPI: https://infisical.wuguishifu.dev/api
  syncConfig:
    resyncInterval: 60s

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: universe
        envSlug: prod
        secretsPath: /tungsten
        recursive: false

  managedSecretReference:
    secretName: tungsten-secrets
    secretNamespace: tungsten
    secretType: Opaque
