apiVersion: v1
kind: ConfigMap
metadata:
  name: gogs-config-template
  namespace: gogs
data:
  app.ini.tmpl: |
    app_name = Gogs
    run_mode = prod

    [repository]
    root = /data/git/repositories

    [server]
    domain       = git.wuguishifu.dev
    http_port    = 3000
    external_url = https://git.wuguishifu.dev/
    disable_ssh  = true

    [database]
    type     = postgres
    host     = postgresql.databases.svc.cluster.local:5432
    name     = gogs
    user     = gogs
    password = ${GOGS_DB_PASSWORD}
    ssl_mode = disable

    [security]
    install_lock = false
    secret_key   = ${GOGS_SECRET_KEY}

    [auth]
    disable_registration = true
    require_signin_view  = false

    [log]
    mode      = console
    level     = info
    root_path = /data/gogs/log
