#!/bin/bash
# Makes this Mac match hosts/mini in the homelab repo, like a tiny ArgoCD:
#   - pulls the repo
#   - for each services/<name>/: installs the pinned release from wuguishifu/universe and
#     (re)starts it under launchd whenever anything in that directory changes
#   - stops services whose directory was removed (their data is kept)
# Runs every minute via launchd (see setup.sh); safe to run by hand. Only logs when it acts.
#
# Knobs, mainly for testing: HOMELAB_HOME, HOMELAB_SKIP_PULL=1, HOMELAB_RELEASE_DIR=<dir of
# <tag>.tar.gz files to install from instead of GitHub>.
set -euo pipefail

HOMELAB_HOME="${HOMELAB_HOME:-$HOME/.homelab}"
REPO_DIR="$HOMELAB_HOME/repo"
HOST_DIR="$REPO_DIR/hosts/mini"
AGENTS_DIR="$HOME/Library/LaunchAgents"
LABEL_PREFIX="dev.wuguishifu.homelab.svc"
RELEASES_REPO="wuguishifu/universe"
KEEP_RELEASES=3
LOG_MAX_BYTES=$((10 * 1024 * 1024))

export PATH="/opt/homebrew/opt/node@22/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
export HOMEBREW_NO_AUTO_UPDATE=1

log() { printf '%s %s\n' "$(date '+%Y-%m-%dT%H:%M:%S')" "$*"; }

# Run from a copy: `git reset` below rewrites this file, and bash reads scripts as it goes.
if [ -z "${HOMELAB_RECONCILE_COPY:-}" ]; then
  cp "$0" "$HOMELAB_HOME/.reconcile.sh"
  HOMELAB_RECONCILE_COPY=1 exec /bin/bash "$HOMELAB_HOME/.reconcile.sh" "$@"
fi

fingerprint() {
  # Everything that should restart the service when it changes.
  local svc_src="$1"
  {
    find "$svc_src" -type f | LC_ALL=C sort | xargs shasum -a 256
    shasum -a 256 "$HOST_DIR/run-service.sh"
  } | shasum -a 256 | cut -d' ' -f1
}

install_release() {
  local name="$1" tag="$2"
  local releases="$HOMELAB_HOME/services/$name/releases"
  local dest="$releases/$tag"
  [ -f "$dest/.installed" ] && return 0

  log "$name: installing $tag"
  mkdir -p "$releases"
  local tmp
  tmp=$(mktemp -d "$releases/.tmp.XXXXXX")
  local tarball="$tmp/bundle.tar.gz"

  if [ -n "${HOMELAB_RELEASE_DIR:-}" ]; then
    cp "$HOMELAB_RELEASE_DIR/$tag.tar.gz" "$tarball"
  else
    local token
    # shellcheck source=/dev/null
    token=$(. "$HOMELAB_HOME/credentials.env" && echo "${GITHUB_TOKEN:?missing from credentials.env}")
    local asset_id
    asset_id=$(curl -fsSL \
      -H "Authorization: Bearer $token" -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/$RELEASES_REPO/releases/tags/$tag" |
      jq -r --arg asset "$tag.tar.gz" '.assets[] | select(.name == $asset) | .id')
    if [ -z "$asset_id" ]; then
      log "$name: release $tag has no $tag.tar.gz asset"
      rm -rf "$tmp"
      return 1
    fi
    # curl drops the Authorization header on the redirect to GitHub's storage host.
    curl -fsSL -H "Authorization: Bearer $token" -H "Accept: application/octet-stream" \
      -o "$tarball" "https://api.github.com/repos/$RELEASES_REPO/releases/assets/$asset_id"
  fi

  mkdir "$tmp/app"
  tar -xzf "$tarball" -C "$tmp/app"

  local bundled
  bundled=$(jq -r '.version' "$tmp/app/release.json")
  if [ "$bundled" != "$tag" ]; then
    log "$name: $tag.tar.gz contains $bundled, refusing to install"
    rm -rf "$tmp"
    return 1
  fi
  local want_node have_node
  want_node=$(jq -r '.node' "$tmp/app/release.json" | sed -E 's/^v([0-9]+).*/\1/')
  have_node=$(node --version | sed -E 's/^v([0-9]+).*/\1/')
  if [ "$want_node" != "$have_node" ]; then
    log "$name: warning: $tag was built for Node $want_node, this host has Node $have_node"
  fi

  (cd "$tmp/app" && corepack pnpm install --prod --ignore-scripts --no-frozen-lockfile --reporter=silent)
  touch "$tmp/app/.installed"
  mv "$tmp/app" "$dest"
  rm -rf "$tmp"
}

# bootout returns immediately but the job stays loaded until the process exits (it gets
# SIGTERM, then SIGKILL after ExitTimeOut), and bootstrapping it again before then fails.
stop_service() {
  local label="$1" exit_timeout="$2"
  local target
  target="gui/$(id -u)/$label"
  launchctl bootout "$target" 2> /dev/null || true
  local waited=0
  while launchctl print "$target" > /dev/null 2>&1; do
    if [ "$waited" -gt "$((exit_timeout + 10))" ]; then
      log "$label: still loaded ${waited}s after bootout"
      return 1
    fi
    sleep 1
    waited=$((waited + 1))
  done
}

write_plist() {
  local name="$1" plist="$2" exit_timeout="$3"
  cat > "$plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by homelab hosts/mini/reconcile.sh. Edit hosts/mini/services/$name instead. -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL_PREFIX.$name</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$HOST_DIR/run-service.sh</string>
    <string>$name</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict><key>HOMELAB_HOME</key><string>$HOMELAB_HOME</string></dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>ExitTimeOut</key><integer>$exit_timeout</integer>
  <key>StandardOutPath</key><string>$HOMELAB_HOME/logs/$name.log</string>
  <key>StandardErrorPath</key><string>$HOMELAB_HOME/logs/$name.log</string>
</dict>
</plist>
EOF
}

reconcile_service() {
  local name="$1"
  local svc_src="$HOST_DIR/services/$name"
  local svc_home="$HOMELAB_HOME/services/$name"
  local label="$LABEL_PREFIX.$name"
  local plist="$AGENTS_DIR/$label.plist"
  mkdir -p "$svc_home/data"

  local fp
  fp=$(fingerprint "$svc_src")
  local running=0
  launchctl print "gui/$(id -u)/$label" > /dev/null 2>&1 && running=1
  if [ "$running" = 1 ] && [ "$(cat "$svc_home/applied" 2> /dev/null)" = "$fp" ]; then
    return 0
  fi

  local tag
  tag=$(tr -d '[:space:]' < "$svc_src/release")
  if [ -f "$svc_src/Brewfile" ] && ! brew bundle check --file="$svc_src/Brewfile" --no-upgrade > /dev/null 2>&1; then
    log "$name: installing Homebrew dependencies"
    brew bundle install --file="$svc_src/Brewfile" --no-upgrade --quiet
  fi
  install_release "$name" "$tag"

  local exit_timeout
  exit_timeout=$(
    # shellcheck source=/dev/null
    . "$svc_src/service.env" && echo "${EXIT_TIMEOUT:-30}"
  )
  mkdir -p "$AGENTS_DIR"
  write_plist "$name" "$plist" "$exit_timeout"
  ln -sfn "releases/$tag" "$svc_home/current"

  # SIGTERM lets in-flight work finish (up to ExitTimeOut) before the new release starts.
  stop_service "$label" "$exit_timeout"
  launchctl bootstrap "gui/$(id -u)" "$plist"
  echo "$fp" > "$svc_home/applied"
  log "$name: running $tag"

  # Keep the running release plus the newest few, for quick rollbacks.
  # shellcheck disable=SC2010,SC2012 # release tags are plain names
  ls -1t "$svc_home/releases" | { grep -vx "$tag" || true; } | tail -n +"$KEEP_RELEASES" | while read -r old; do
    rm -rf "${svc_home:?}/releases/$old"
  done
}

# --- per-service mode: a separate process, so `set -e` works and one failure doesn't stop the rest
if [ "${1:-}" = "service" ]; then
  reconcile_service "$2"
  exit 0
fi

# --- main -----------------------------------------------------------------------------------
LOCK="$HOMELAB_HOME/reconcile.lock"
find "$LOCK" -maxdepth 0 -mmin +30 -exec rmdir {} \; 2> /dev/null || true
if ! mkdir "$LOCK" 2> /dev/null; then
  exit 0 # another run is in progress
fi
trap 'rmdir "$LOCK"' EXIT

if [ "${HOMELAB_SKIP_PULL:-0}" != 1 ]; then
  git -C "$REPO_DIR" fetch --quiet origin main
  git -C "$REPO_DIR" reset --quiet --hard origin/main
fi

for svc_src in "$HOST_DIR"/services/*/; do
  [ -d "$svc_src" ] || continue
  name=$(basename "$svc_src")
  if ! /bin/bash "$0" service "$name"; then
    log "$name: reconcile failed; the previous version (if any) is still running"
  fi
done

# Stop services whose directory was removed from the repo. Data and releases are kept.
for plist in "$AGENTS_DIR/$LABEL_PREFIX".*.plist; do
  [ -e "$plist" ] || continue
  name=$(basename "$plist" .plist)
  name=${name#"$LABEL_PREFIX".}
  [ -d "$HOST_DIR/services/$name" ] && continue
  stop_service "$LABEL_PREFIX.$name" "$(plutil -extract ExitTimeOut raw "$plist" 2> /dev/null || echo 30)" || true
  rm -f "$plist" "$HOMELAB_HOME/services/$name/applied"
  log "$name: removed from the repo, stopped (data kept in $HOMELAB_HOME/services/$name)"
done

# launchd appends to log files, so copy-and-truncate keeps them bounded.
for f in "$HOMELAB_HOME"/logs/*.log; do
  [ -f "$f" ] || continue
  if [ "$(stat -f %z "$f")" -gt "$LOG_MAX_BYTES" ]; then
    cp "$f" "$f.1" && : > "$f"
  fi
done
