#!/bin/bash
# Bootstraps the Mac mini as a homelab host. Safe to re-run. Run it on the mini itself:
#   curl -fsSL https://raw.githubusercontent.com/wuguishifu/homelab/main/hosts/mini/setup.sh | bash
# or, once the repo is cloned: bash ~/.homelab/repo/hosts/mini/setup.sh
# Needs ~/.homelab/credentials.env first (see README.md).
set -euo pipefail

HOMELAB_HOME="${HOMELAB_HOME:-$HOME/.homelab}"
REPO_URL="https://github.com/wuguishifu/homelab.git"
LABEL="dev.wuguishifu.homelab.reconcile"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
export PATH="/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export HOMEBREW_NO_AUTO_UPDATE=1

command -v brew > /dev/null || { echo "Homebrew is required: https://brew.sh" >&2; exit 1; }

mkdir -p "$HOMELAB_HOME/logs" "$HOMELAB_HOME/services"
chmod 700 "$HOMELAB_HOME"

creds="$HOMELAB_HOME/credentials.env"
if [ ! -f "$creds" ]; then
  cat >&2 << EOF
Missing $creds. Create it (chmod 600) with:
  INFISICAL_CLIENT_ID=...      # machine identity with read access to the services' secrets
  INFISICAL_CLIENT_SECRET=...
  GITHUB_TOKEN=...             # fine-grained token: wuguishifu/universe, Contents: read-only
EOF
  exit 1
fi
chmod 600 "$creds"

if [ ! -d "$HOMELAB_HOME/repo/.git" ]; then
  git clone --quiet "$REPO_URL" "$HOMELAB_HOME/repo"
fi

echo "Installing host dependencies"
brew bundle install --file="$HOMELAB_HOME/repo/hosts/mini/Brewfile" --no-upgrade --quiet

# Unattended-server settings. Changing them needs sudo, so only warn.
pmset -g | grep -qE '^ sleep +0' || echo "warning: system sleep is on (fix: sudo pmset -a sleep 0)"
pmset -g | grep -qE '^ autorestart +1' || echo "warning: no restart after power loss (fix: sudo pmset -a autorestart 1)"
fdesetup status | grep -q 'Off' || echo "warning: FileVault is on, so services won't start after a reboot until someone logs in"

cat > "$PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by homelab hosts/mini/setup.sh. -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$HOMELAB_HOME/repo/hosts/mini/reconcile.sh</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict><key>HOMELAB_HOME</key><string>$HOMELAB_HOME</string></dict>
  <key>RunAtLoad</key><true/>
  <key>StartInterval</key><integer>60</integer>
  <key>StandardOutPath</key><string>$HOMELAB_HOME/logs/reconcile.log</string>
  <key>StandardErrorPath</key><string>$HOMELAB_HOME/logs/reconcile.log</string>
</dict>
</plist>
EOF
launchctl bootout "gui/$(id -u)/$LABEL" 2> /dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo "Reconciler installed; it runs now and every minute. Follow it with:"
echo "  tail -f $HOMELAB_HOME/logs/reconcile.log"
